---
title: "Topic modeling analysis of Buenrostro et al (2018) data with k = 8 topics"
author: Peter Carbonetto
output: workflowr::wflow_html
---

*Add text here.*

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,results = "hold",
                      fig.align = "center",dpi = 120)
```

Load the packages used in the analysis.

```{r load-pkgs, message=FALSE}
library(Matrix)
library(fastTopics)
library(ggplot2)
library(cowplot)
```

Load the count data and the $k = 8$ multinomial topic model fit to
these data:

```{r load-data}
load("data/Buenrostro_2018/processed_data/Buenrostro_2018_binarized.RData")
fit <- readRDS(
  file.path("output/Buenrostro_2018/binarized/filtered_peaks",
            "fit-Buenrostro2018-binarized-filtered-scd-ex-k=8.rds"))$fit
fit <- poisson2multinom(fit)
```

Visualize the structure identified in the FACS cell populations using
a Structure plot:

```{r structure-plot, fig.height=1.5, fig.width=8, message=FALSE}
set.seed(1)
celltypes = factor(samples$label,
                   c("CLP","pDC","LMPP","HSC","MPP","CMP","MEP","GMP",
				     "mono","UNK"))
topic_colors <- c("skyblue","orchid","gainsboro","red","darkblue",
                  "darkorange","forestgreen","limegreen")
custom_embed_method <- function (fit, ...) {
  y0 <- pca_from_topics(fit,dims = 1)
  return(tsne_from_topics(fit,dims = 1,Y_init = matrix(y0),eta = 30,
         perplexity = 70,...))
}
p <- structure_plot(fit,grouping = celltypes,n = Inf,gap = 20,
               verbose = FALSE,colors = topic_colors,
			   topics = c(1,6,3,5,8,7,2,4),
               embed_method = custom_embed_method)
```
