---
title: "Identify clusters from PC plots in Cusanovich et al (2018) data"
author: Peter Carbonetto
output: workflowr::wflow_html
---

*Add summary text here.*

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,results = "hold",
                      fig.align = "center",dpi = 120)
```
					  
Load packages and some functions used in this analysis.

```{r load-pkgs}
library(Matrix)
library(ggplot2)
library(cowplot)
library(fastTopics)
source("code/plots.R")
```

Load data. The UMI counts are no longer needed at this stage of the
analysis.

```{r load-data}
load("data/Cusanovich_2018.RData")
rm(counts)
```

Load the $k = 10$ Poisson NMF fit.

```{r load-fit}
fit <- readRDS("output/fit-Cusanovich2018-scd-ex-k=10.rds")$fit
```

Plot PCs of the topic proportions.

```{r pca-1, fig.width=5, fig.height=5}
p1 <- basic_pca_plot(fit,1:2)
p2 <- basic_pca_plot(fit,3:4)
p3 <- basic_pca_plot(fit,5:6)
p4 <- basic_pca_plot(fit,7:8)
plot_grid(p1,p2,p3,p4)
```

These next plots visualize the same results, but as 2-d histograms:

```{r pca-2, fig.width=5, fig.height=5}
p5 <- pca_hexbin_plot(fit,1:2) + guides(fill = "none")
p6 <- pca_hexbin_plot(fit,3:4) + guides(fill = "none")
p7 <- pca_hexbin_plot(fit,5:6) + guides(fill = "none")
p8 <- pca_hexbin_plot(fit,7:8) + guides(fill = "none")
plot_grid(p5,p6,p7,p8)
```

Layer the tissues onto the scatterplots. PCs 1 and 2:

```{r pca-3, fig.width=8, fig.height=2}
p9 <- labeled_pca_plot(fit,1:2,samples$tissue,legend_label = "tissue")
p10 <- labeled_pca_plot(fit,1:2,samples$cell_label,legend_label = "cell_label")
plot_grid(p9,p10,rel_widths = c(2,3))
```

PCs 3 and 4:

```{r pca-4, fig.width=8, fig.height=2}
p11 <- labeled_pca_plot(fit,3:4,samples$tissue,legend_label = "tissue")
p12 <- labeled_pca_plot(fit,3:4,samples$cell_label,legend_label = "cell_label")
plot_grid(p11,p12,rel_widths = c(2,3))
```

PCs 5 and 6:

```{r pca-5, fig.width=8, fig.height=2}
p13 <- labeled_pca_plot(fit,5:6,samples$tissue,legend_label = "tissue")
p14 <- labeled_pca_plot(fit,5:6,samples$cell_label,legend_label = "cell_label")
plot_grid(p13,p14,rel_widths = c(2,3))
```

PCs 7 and 8:

```{r pca-6, fig.width=8, fig.height=2}
p15 <- labeled_pca_plot(fit,7:8,samples$tissue,legend_label = "tissue")
p16 <- labeled_pca_plot(fit,7:8,samples$cell_label,legend_label = "cell_label")
plot_grid(p15,p16,rel_widths = c(2,3))
```
