---
title: "Topic modeling analysis of single-cell ATAC-seq data"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Topic modeling analysis of single-cell ATAC-seq data

* [Literatures of scATAC-seq papers](references.html)

* Topic modeling analysis for Cusanovich 2018 single cell ATAC-seq dataset
    - [About Cusanovich 2018 dataset](scATACseq_data_Cusanovich2018.html)
    - [Process Cusanovich 2018 dataset](process_data_Cusanovich2018.html)
    - [Assess model fits](assess_fits_Cusanovich2018.html)
    - [PCA plots of topic proportions](compare_pca_clusters_Cusanovich2018.html)
    - [Visualize topics](plots_Cusanovich2018.html)
    - [Clustering by topic proportions (K=13)](clusters_Cusanovich2018_k13.html)
    - [Motif enrichment and gene analysis (K=13)](motif_gene_analysis_Cusanovich2018.html)

* Topic modeling analysis for Buenrostro 2018 single cell ATAC-seq dataset
    - [Process Buenrostro 2018 dataset](process_data_Buenrostro2018.html)
    - [Assess model fits](assess_fits_Buenrostro2018.html)
    - [PCA plots of topic proportions](compare_pca_clusters_Buenrostro_2018.html)
    - [Clustering by topic proportions (K=11) with Chen2019 processed data](clusters_Buenrostro2018_k11_Chen2019pipeline.html)
    - [Clustering by topic proportions (K=11) with chromVAR processed data](clusters_Buenrostro2018_chomVAR_scPeaks.html)
    - [Motif enrichment and gene analysis (K=11) with Chen2019 processed data](motif_gene_analysis_Buenrostro2018_Chen2019pipeline.html)
    - [Motif enrichment and gene analysis (K=11) with chromVAR processed data](motif_gene_analysis_Buenrostro2018_chomVAR_scPeaks.html)

* Topic modeling analysis for Lareau 2019 single cell ATAC-seq dataset
    - [About Lareau 2019 dataset](scATACseq_data_Lareau2019.html)
    - [Process Lareau 2019 dataset](process_data_Lareau2019.html)
    - [Assess model fits](assess_fits_Lareau2019_bonemarrow.html)
    - [PCA plots of topic proportions](compare_pca_clusters_Lareau_2019_bonemarrow.html)
    - [Clustering by topic proportions (K=13)](clusters_Lareau2019_bonemarrow_k13.html)
