library(fastTopics)
library(ggplot2)
library(cowplot)
load(file.path("output/Cusanovich_2018/tissues",
               "de-gene-cusanovich2018-kidney-k=10.RData"))
n             <- nrow(de_gene$postmean)
de_gene$f0    <- rep(0,n)
de_gene$lower <- with(de_gene,postmean - se)
de_gene$upper <- with(de_gene,postmean + se)
p1 <- volcano_plot(de_gene,k = 8,ymax = 20)
p2 <- volcano_plot(de_gene,k = 3,ymax = 20)
p3 <- volcano_plot(de_gene,k = 1,ymax = 20)
p4 <- volcano_plot(de_gene,k = 4,ymax = 20)
volcano_plotly(de_gene,k = 3)
